image: docker:latest

stages:
  - test
  - build

test_api:
  stage: test
  script:
    - docker-compose -f api/test.yml build
    - docker-compose -f api/test.yml run test

  tags:
    - dind

build_front:
  stage: build
  script:
    - docker-compose -f dev.yml front rm dist/*
    - docker-compose -f dev.yml front npm run build
  artifacts:
    paths:
      - front/dist
  only:
    - master
    - develop
  tags:
    - dind
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
# variables:
#   DOCKER_DRIVER: overlay
#
# services:
# - docker:dind
#
#
# # build:
# #   stage: build
# #   script:
# #   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
# #   - docker build -t funkwhale/front .
# #   - docker push
# #
# #   tags:
# #     - dind
# #   only:
# #     - master
