version: '2'
services:
  test:
    build:
      dockerfile: docker/Dockerfile.test
      context: .
    command: pytest
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - "DJANGO_ALLOWED_HOSTS=localhost"
      - "DATABASE_URL=postgresql://postgres@postgres/postgres"
      - "FUNKWHALE_URL=https://funkwhale.test"
      - "CACHEOPS_ENABLED=False"
  postgres:
    image: postgres
